# SwiftLint Configuration for PeekOCR
# macOS Native App with Swift/SwiftUI

# Paths to exclude from linting
excluded:
  - build/
  - .build/
  - Pods/
  - DerivedData/
  - .swiftpm/
  - Package.swift

# Disabled rules
disabled_rules:
  - line_length
  - trailing_whitespace
  - identifier_name

# Opt-in rules (additional rules not enabled by default)
opt_in_rules:
  # Security
  - force_unwrapping
  - force_cast

  # Style
  - closure_spacing
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
file_length:
  warning: 150
  error: 200
  ignore_comment_only_lines: true

type_body_length:
  warning: 250
  error: 350

function_body_length:
  warning: 50
  error: 80

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

large_tuple:
  warning: 3
  error: 4

vertical_whitespace:
  max_empty_lines: 2

trailing_comma:
  mandatory_comma: false

colon:
  apply_to_dictionaries: true

# SwiftUI specific - allow multiple closures in View builders
multiple_closures_with_trailing_closure:
  severity: warning

# Custom rules for SwiftUI patterns
custom_rules:
  swiftui_state_private:
    name: "SwiftUI State Private"
    regex: "(?<!private )@State\\s+var"
    message: "@State properties should be private"
    severity: warning

  swiftui_stateobject_private:
    name: "SwiftUI StateObject Private"
    regex: "(?<!private )@StateObject\\s+var"
    message: "@StateObject properties should be private"
    severity: warning
